# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#
# Answer: 4613732

max = 4000000
sum = 0

a = 1
b = 2

while(b <= max):
  sum += b
  a += b * 2      # a, b, a + b, a + 2b, 2a + 3b
  b = a * 2 - b   # b = (a + 2b) * 2 - b
    
print sum
