# Triangular, pentagonal, and hexagonal
# Problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#
#   Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
#   Pentagonal  Pn=n(3n-1)/2  1, 5, 12, 22, 35, ...
#   Hexagonal   Hn=n(2n-1)    1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
#
# Answer: 1533776805

from math import sqrt, trunc

i = 143

while True:
  i += 1
  h = i * (2*i-1) * 2
  
  # triangle check
  # j^2 <= h < (j+1)^2
  j = trunc(sqrt(h))
  if h != j*(j+1):
    continue
    
  # pentagonal check
  # 3n^2 - n - h = 0
  j = 1 + 12 * h
  k = trunc(sqrt(j))
  if k*k != j:
    continue
  
  if (k+1)%6==0:
    print i,h/2
    break
  
  
  